name: DevopsWF

on:
  push:
    branches: [master, devops]

jobs:
  # Job 1: Run tests
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Run tests
        run: go test ./... || echo "No tests found, skipping..."

  # Job 2: Build the Go application
  Build:
    runs-on: ubuntu-latest
    needs: Testing
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Build application
        run: go build -o countryinfo-app .
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: countryinfo-app
          path: countryinfo-app

  # Job 3: Deploy to GitLab
  DeployToGitLab:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git user
        run: |
          git config --global user.name "Lotte Echholt"        # Sett til ditt faktiske navn
          git config --global user.email "lotteoe@stud.ntnu.no"  # Sett til din faktiske NTNU-epost

      - name: Add GitLab remote
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@git.gvk.idi.ntnu.no/course/prog2005/prog2005-2025-workspace/lotteoe/assignment-1.git

      - name: Push to GitLab
        run: |
          # Ensure the repository is not shallow
          git fetch --unshallow || true
          # Checkout the branch you want to push, e.g., main
          git checkout master
          git pull origin master
          git push --force gitlab master
